Algoritmo "QUESTÃO 1"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 30/08/2023
Var
   // Seção de Declarações das variáveis
   a : inteiro
   b : inteiro
   c : inteiro
   soma : inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...

   // Pedindo dados ao usuário.

   escreva("Digite o valor do primeiro número: ")
   leia (a)

   escreva("Digite o valor do segundo número: ")
   leia (b)

   escreva("Digite o valor do terceiro número: ")
   leia (c)

   limpatela
   
   // Definindo calculos

   soma <- a + b

   // Mostrando ao usuário o resultado na tela.

   se (soma < c)entao
      escreval (soma, " é menor que", c)
   senao
      escreval (soma, " é maior que", c)
   fimse

Fimalgoritmo
